package Data;

/**
* Data/EventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Data.idl
* lunedì 28 aprile 2014 1.52.30 CEST
*/

public final class EventHolder implements org.omg.CORBA.portable.Streamable
{
  public Data.Event value = null;

  public EventHolder ()
  {
  }

  public EventHolder (Data.Event initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Data.EventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Data.EventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Data.EventHelper.type ();
  }

}
