package Data;


/**
* Data/Event.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Data.idl
* lunedì 28 aprile 2014 1.52.30 CEST
*/

public final class Event implements org.omg.CORBA.portable.IDLEntity
{
  public int number = (int)0;
  public String description = null;

  public Event ()
  {
  } // ctor

  public Event (int _number, String _description)
  {
    number = _number;
    description = _description;
  } // ctor

} // class Event
